version: '3.9'
services:
  db:
    image: postgres:15
    container_name: planten-db
    restart: always
    environment:
      POSTGRES_PASSWORD: planten123
      POSTGRES_DB: planten
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:planten123@db:5432/planten
    depends_on:
      - db
volumes:
  db-data:
