name: spotify_qr_player
description: Minimal app to scan QR and play Spotify track.
version: 1.0.0
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_web_auth: ^0.3.2
  http: ^0.13.4
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
